server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/User_microservice
    username: emazon
    password: user123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

appDescription: "Users API"
appVersion: "1.0.0"




